language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
addons:
  code_climate:
    repo_token:
      secure: "wyqdsAQ5OP9ZJenDP2VORBSLhap/7tUvuE2BVprMfGgpYmEyLsby4lAOWk0USmebfZCxX9TyvrgkFbxep9dh9kP+tAVZhvHQi/obm4PCz9NczaltE7WvGBiizVN+tXRG+HL7FR9HnK9/Z2x7ML64i0amkPpIKJew7hQDFT0XXYQ="
