language: ruby
rvm:
  - 2.0.0
  - 2.1.0
addons:
  code_climate:
    repo_token:
      secure: "q8UtQbfRqajnxVYik1JMDSXhi0GYeg0L3Gu0AY9jEhNbodk30Y9Dv1CHeprggMbJDOVT/Aj3nxJm3+CXVvOquFOimC767ZUegICqRAPcJO/AFeuhlHhP99jlJ+/86zzbQMQrIi9GL4D3DQm9Gp/70eCwk5aXdwkpXq7IiU0wjjc="
